# Generated by Django 3.2.20 on 2023-09-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
